language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - "pip install ."
  - "pip install nose2"
  - "pip install python-coveralls"
  - "pip install cov-core"
script:
  "nose2 -C"
after_success:
  - "coveralls -d .coverage"
