language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install ."
  - "pip install nose2"
  - "pip install python-coveralls"
script:
  "nose2"
after_success:
  - "coveralls"
